

#chiamata semplice non protetta
# curl -i http://localhost:8080/arealo
GET http://localhost:8080/arealo

###

# curl -i -u cameraten@example.com:secretpassword http://localhost:8080/users
GET http://localhost:8080/users
Authorization: Basic cameraten@example.com secretpassword

###
# curl -i -u cameraten@example.com:secretpassword http://localhost:8080/users
GET http://localhost:8080/users
Authorization: Basic marcobona@example.com mysecretpwd

###


# curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -d '{"firstName": "Mario", "lastName": "Cario", "email": "marioCario@example.com", "password": "mysecretpwd"}' http://localhost:8080/saveUser
POST http://localhost:8080/saveUser
Accept: application/json
Content-Type: application/json

{
  "firstName": "Marco",
  "lastName": "Bona",
  "email": "marcobona@example.com",
  "password": "mysecretpwd"
}

###

# curl -X POST -H "Content-Type: application/json" -d '{"name": "CardName"}' http://localhost:8080/save
POST http://localhost:8080/save
Authorization: Basic cameraten@example.com secretpassword
Content-Type: application/json

{
  "name": "Mulldrotha"
}

###







