# curl -i -u utente:pwd http://localhost:8080/
GET http://localhost:8080/
Authorization: Basic utente pwd

###

# curl -i -X POST -H "Content-Type: application/json" -u utente:pwd -d '{"name": "Nome della carta"}' http://localhost:8080/save
POST http://localhost:8080/save
Authorization: Basic utente pwd
Content-Type: application/json

{
  "name": "Nome della carta5"
}

###

# curl -i -X POST -H "Content-Type: application/json" -d '{"name": "Nome della carta"}' http://localhost:8080/save
POST http://localhost:8080/save

Content-Type: application/json
{
  "name": "Nome della carta4"
}

###

GET http://localhost:8080/cards
Authorization: Basic utente pwd

