
# curl -i -X POST -H "Content-Type: application/json" -u utente:pwd -d '{"name": "Nome della carta"}' http://localhost:8080/save
GET http://localhost:8080/cards
Authorization: Basic mike important


###

# curl -i -u mike:important http://localhost:8080/
POST http://localhost:8080/save
Authorization: Basic mike important
Content-Type: application/json

{
  "name": "Nome della carta"
}
###


# curl -i -u henrik:important http://localhost:8080/cantina/menu/today
GET http://localhost:8080/
Authorization: Basic henrik important

###


# curl -u cameraten@example.com:password http://localhost:8080/users
GET http://localhost:8080/users
Authorization: Basic cameraten@example.com secretpassword

###


